### ISSUE TITLE
Failure during compile in info-sdk for iOS

### ISSUE THREAD

**Issue by yahooooza** [schneiderma/blukii_developer#1]
I installed the library like described but having problems compiling the app after importing with cocoa. The first issue a ran into is that the library is compiled with Swift 5.0.1 but cannot be imported by the swift 5.2.4 compiler. 
A quick google search let me found out that i have to set the "Build Libraries for Distribution" Build Option to true. But when i do that( even after cleaning the build folder) i get the error:

error: using bridging headers with module interfaces is unsupported
Command CompileSwiftSources failed with a nonzero exit code

Is this failure known and when yes can it be fixed without changing the Swift Compiler? Or is that the only way of getting the sdk to work?

Thanks

**Comment by lennart683** [comment]
Please check if you are using the new Version 2.0.4. In this Version the "Build Libraries for Distribution" is set to true. This version should work with Swift Version 5.2.4

To update the cocoapod run this commands:
`cd <path of Podfile>`
`pod repo update`
`pod update`

**Comment by yahooooza** [comment]
Hi,
thanks. That Info helped. My Deployment Target was set to iOS 8 by Default and therefore cocoa installed the old version 1.0.6 . I was wondering why the Documentation was completly wrong. My first time developing for iOS. Now i'm Reinstalling the newest version of Xcode and check if everthing is working. BTW Downgrade to Xcode 10.3 helped, but the code structure seemed to be changed quite significantly and so im starting revere engineering to get the code working ;).
